micronaut:
  application:
    name: friday
  router:
    static-resources:
      default:
        enabled: true
        paths: classpath:public
        mapping: /**
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:file:./db/friday`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:root}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
