micronaut:
  application:
    name: friday
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:file:./db/friday;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:root}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
