micronaut:
  application:
    name: friday
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    entity-scan.packages:
      - 'com.notkamui'
jpa.default.properties.hibernate.hbm2ddl.auto: update
